### PR TITLE
Fixes for 410

### PR DESCRIPTION
**Pull request by tuxmea**
Major changes - new version required !!
Adoptions for types and providers to work on OpenNebula 4.10
Adoptions for sunstone to work on systems without internet access.

### CODE REVIEW

**Comment by rwaffen** [comment]
before we merge, we should add a tag, or am i wrong?

**Comment by tuxmea** [comment]
Either way should work.
Setting new tag first might be more transparent.

**Comment by rwaffen** [comment]
okay, I will make a tag and than merge your PR.

**Comment by rwaffen** [comment]
Sooooo... tag v1.0.2 is released
will merge now... :boom:

**Pull request merged**
