### PR TITLE
Remove usage of validate_integer for compatibility with older stdlib

### PR DESCRIPTION
**Pull request by michael-os**

### CODE REVIEW

**Comment by rwaffen** [comment]
hmm, looks okay... but is there no other way to get this working with older versions?

**Comment by tuxmea** [comment]
No good.
Never simply remove datavalidation.
Please use is_integer function from stdlib which was introduced in stdlib 2.1.
This should be old enough.

**Comment by michael-os** [comment]
Well, one could use is_integer and possibly additional manual range checks to achieve the same functionliality. Or we could check if we can update our stdlib to version 4.6.0, but I guess that's not something we do in a snap? @tuxmea @nmesstorff ?

**Comment by michael-os** [comment]
Apart from the pending travis-build, are you ok with this updated PR, @rwaffen @tuxmea ?

**Comment by rwaffen** [comment]
looks a bit complicated but okay...

**Comment by rwaffen** [comment]
@michael-os what do you think, first merge this one here or #151 ?

**Comment by tuxmea** [comment]
OK for me.

**Comment by michael-os** [comment]
@rwaffen yeah, that's why I didn't want to do it when I noticed that the validate_integer function has become available only recently :smile: 
As far as #151 is concerned just go ahead and merge your change first. I can rebase mine afterwards

**Comment by rwaffen** [comment]
oh, one can merge this one without rebase...

**Pull request merged**
