### PR TITLE
Restricted find depth in backup script

### LINKED ISSUE #258: Backup script produces errors on nfs mounts
When automated like this (names and addresses changed for data privacy's sake):
```
[admin@server1 ~]$ crontab -l
...
# Puppet Name: one_db_backup
0 * * * * /var/lib/one/bin/one_db_backup.sh
```
and writing to an nfs share like this:
```
[root@server1 ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/rootdg-LogVol00
                      3.9G  1.3G  2.4G  36% /
tmpfs                 1.9G     0  1.9G   0% /dev/shm
/dev/mapper/rootdg-LogVol08
                      976M  1.3M  924M   1% /admin
/dev/mapper/rootdg-LogVol07
                      120M  1.6M  113M   2% /audit
/dev/vda1             283M  148M  120M  56% /boot
/dev/mapper/rootdg-LogVol04
                      969M  1.7M  917M   1% /home
/dev/mapper/rootdg-LogVol03
                      1.9G   25M  1.8G   2% /opt
/dev/mapper/rootdg-LogVol05
                      2.0G   30M  1.8G   2% /tmp
/dev/mapper/rootdg-LogVol02
                      2.0G  500M  1.4G  27% /var
/dev/mapper/rootdg-LogVol06
                      2.0G  3.0M  1.9G   1% /var/cores
/dev/mapper/rootdg-LogVol01
                      2.0G  285M  1.6G  16% /var/log
192.168.20.21:/server1_inf_backup
                      100G  474M  100G   1% /var/lib/one/nfs_backup
192.168.20.21:/server1_inf_datastore_0
                      200G   94G  107G  47% /var/lib/one/datastores/0
192.168.20.21:/server1_inf_datastore_1
                      500G  415G   86G  83% /var/lib/one/datastores/1
192.168.20.21:/server1_inf_datastore_2
                     1014M  4.3M 1010M   1% /var/lib/one/datastores/2
```
the backup script produces errors like this:
```
From root@server1.inf.ourdomain.de  Fri Dec 22 12:00:03 2017
Return-Path: <root@server1.inf.ourdomain.de>
X-Original-To: admin
Delivered-To: admin@server1.inf.ourdomain.de
Received: by server1.inf.ourdomain.de (Postfix, from userid 9869)
	id 03EC71625; Fri, 22 Dec 2017 12:00:03 +0100 (CET)
From: root@server1.inf.ourdomain.de (Cron Daemon)
To: admin@server1.inf.ourdomain.de
Subject: Cron <admin@server11> /var/lib/one/bin/one_db_backup.sh
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <LC_ALL=en_US.utf-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/var/lib/one>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=admin>
X-Cron-Env: <USER=admin>
Message-Id: <20171222110003.03EC71625@server1.inf.ourdomain.de>
Date: Fri, 22 Dec 2017 12:00:03 +0100 (CET)

find: `/var/lib/one/nfs_backup/.nfs': Permission denied
```

The reason for this is that the script does not limit its file selection to the backup directory but descends into any subdirectories below. The .nfs subdirectory belongs to root, however, and has restrictive permissions (as it should):
```
[root@serverd1 nfs_backup]# ls -la .nfs
total 36
drwxrwx--- 4 root     root        41 Dec 18 09:20 .
drwxr-xr-x 3 admin admin 28672 Jan  3 09:00 ..
drwx------ 2 root     root         6 Nov  1 10:50 rmt
-rw-r--r-- 1 root     root        97 Dec 18 09:24 rmtab
drwxrwx--- 4 root     root        40 Oct 26 20:00 .sm.ha
[root@server1 nfs_backup]#
```

A simple fix would be to restrict the find operation to the backup dir itself.

### PR DESCRIPTION
**Pull request by csage**
Fixes #258.

### CODE REVIEW

**Comment by csage** [comment]
No idea why this breaks the tests, and unfortunately I do not have the time to debug this. My apologies. I'll leave it open anyway, at least for the moment.

**Comment by Xylakant** [comment]
@csage Looks like the inifile module in the fixtures was updated to a version that's no longer ruby 1.8.7 compatible:

´´´´
 1) one::oned::config On CentOS 6 without kvm driver emulator settings should not contain Ini_setting[set_kvm_driver_emulator]
     Failure/Error: it { should_not contain_ini_setting('set_kvm_driver_emulator') }
     Puppet::Error:
       Could not autoload puppet/type/ini_setting: /home/travis/build/epost-dev/opennebula-puppet-module/spec/fixtures/modules/inifile/lib/puppet/type/ini_setting.rb:22: syntax error, unexpected ':', expecting ')'
         newparam(:name, namevar: true) do
´´´´

That's most likely not your fault but rather the testsuites problem.

**Comment by csage** [comment]
@Xylakant Thanks a lot for sussing this out. I've now pinned the offending module at version 2.1.0, which appears to be the last version that is compatible with Ruby 1.8.7. 

Unfortunately, the Travis build errored out because of infrastructure problems - the tests passed locally, and all of the ones that ran through to their respective ends passed on Travis as well. As I lack the permissions to do so, could I prevail on you to kick off the build a second time so as to make it pass?

Then this should hopefully fix both #258 and #260 now.

**Comment by Xylakant** [comment]
Sure, will do tomorrow. Remind me if I forget.

**Comment by Xylakant** [comment]
There's at least another build failure due to a dependency problem in here https://travis-ci.org/epost-dev/opennebula-puppet-module/jobs/325171749

seems like bundler resolves the version for nokogiri to a higher version in that test run.

**Comment by csage** [comment]
Yes, I saw. No idea why that happened now. As the Nokogiri version it now resolved to was published way before the last green test runs in the project, it feels like it should have turned up before.

Anyway, unfortunately other things took priority. I'll try to make time for this the coming week. And thanks for reminding me. :-)

**Comment by Xylakant** [comment]
closing in favor of #263

**Pull request closed without merging**
