### PR TITLE
Puppet4 deprecates template dynamic variable lookup

### PR DESCRIPTION
**Pull request by tuxmea**
add puppet4 to travis checks

### CODE REVIEW

**Comment by tuxmea** [comment]
@sebastian-su can you please explain the jenkins error?

**Comment by sebastian-su** [comment]
@tuxmea weird indeed. Looks like a problem while downloading the package. Retriggering...

retest this please

**Comment by tuxmea** [comment]
@sebastian-su no another package fails:
Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install opennebula-node-kvm' returned 1: Error: failure: repodata/0dbfee271bfa5fccd4f6ff91c321b59994a2dad2b7c2bb6f9cde7eb0b394ab42-filelists.sqlite.bz2 from epel: [Errno 256]

**Comment by sebastian-su** [comment]
@tuxmea by saying: "retest this please" 

Not sure whats wrong - I had trouble running the tests locally today too. Maybe they have trouble with the mirrors.

**Pull request merged**
