### PR TITLE
oneflow service name in 4.12 is opennebula-flow

### PR DESCRIPTION
**Pull request by jtriley**

### CODE REVIEW

**Comment by sebastian-su** [comment]
Can one of the admins verify this patch?

**Comment by tuxmea** [comment]
@jtriley many thanks for the patch. can you please also adopt the spec tests?

**Comment by jtriley** [comment]
@tuxmea my bad - should be all set now.

**Comment by tuxmea** [comment]
@jtriley many thanks. @sebastian-su ready for merge.

**Comment by sebastian-su** [comment]
Tests are fine. Merging...
@jtriley thanks!

**Pull request merged**
