### PR TITLE
Fix onegate endpoint in oned.conf

### PR DESCRIPTION
**Pull request by jnoss**
This PR fixes setting ONEGATE_ENDPOINT in oned.conf and also adds a parameter called oned_onegate_endpoint that can be used to override the default "http://<oned_onegate_ip>:5030" if needed (such as if using ssl proxy)

### CODE REVIEW

**Comment by rwaffen** [comment]
damn, there is still the "bug" that ruby 1.8.7 is not supported by rake 11.x. (this is by intension, rake dropped support for ruby1.8.7 with version 11.x)

we should fix that in the Gemfile

**Comment by tuxmea** [comment]
@jnoss please replace gem 'rake' with the following code in Gemfile:
```
if RUBY_VERSION < '1.9.3'
  rakeversion = '< 11'
else
  rakeversion = '> 10'
end
gem 'rake', rakeversion
```

**Comment by tuxmea** [comment]
Build fixed in #231

**Comment by Xylakant** [comment]
closing in favor of #241 which contains a rebased and fixed version of this PR

**Pull request closed without merging**
