### PR TITLE
switch package declaration to ensure_packages

### PR DESCRIPTION
**Pull request by jnoss**
Switch this declaration from package to ensure_packages for module compatibility.

### CODE REVIEW

**Comment by rwaffen** [comment]
i strongly recommend to not use any ensure_* functions. you only get in trouble with them. specially when you think about containment, chaining, ordering...

**Comment by jtriley** [comment]
Would you be opposed to declaring https://forge.puppetlabs.com/saz/sudo as a dependency and then using:

```
class { 'sudo':
  purge               => false,
  config_file_replace => false,
}
```
in place of `Package['sudo']`? This would allow folks to require sudo in other places without resource conflicts...

**Comment by jtriley** [comment]
... assuming they don't mind using saz/sudo of course...

**Comment by rwaffen** [comment]
i'll discuss this tomorrow with some colleagues of mine... someone other had asked the same in the past...

**Comment by tuxmea** [comment]
Like robert mentioned: dont use create_resources.
Can you send a pull request for using saz-sudo?

**Comment by rwaffen** [comment]
so we agree to close this one and you prepare one with saz/sudo?

**Comment by jtriley** [comment]
@rwaffen Yep sounds good. Thanks!

**Pull request closed without merging**
