### PR TITLE
update ini_settings with empty section

### LINKED ISSUE #197: new kvm driver config handling continuously appends and breaks syntax
The recent change to kvm driver config isn't working properly. When both the kvm emulator and nic settings are specified it doesn't idempotently make the updates and instead constantly appends to the file every time puppet runs. Even worse it's appending the wrong output (ie `[]` on a line by itself) which causes a syntax error:

```
[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm

[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm

[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm

[]
NIC = [ filter = "clean-traffic", model="virtio" ]

[]
EMULATOR = /usr/libexec/qemu-kvm
```

Error in logs:

```
Thu Sep 10 11:23:43 2015 [Z0][VMM][I]:  Loading driver: kvm (KVM)
Thu Sep 10 11:23:43 2015 [Z0][VMM][E]: Error loading driver configuration file /etc/one/vmm_exec/vmm_exec_kvm.conf : syntax error, unexpected CBRACKET, expecting $end at line 60, columns 2797:2799
```

### PR DESCRIPTION
**Pull request by rwaffen**
- fix #197

### CODE REVIEW

**Comment by jtriley** [comment]
Did you test this? I haven't had a chance yet but the docs for inifile says the default value of section is `''`:

https://github.com/puppetlabs/puppetlabs-inifile#section

**Comment by rwaffen** [comment]
yes, i tested this. there i had to do the changes for dockerfile and vagrantfile.
i ran puppet several times and it was only set one time, when set hiera variables are set.

**Comment by rwaffen** [comment]
i set up hiera in the vagrant (only quick, have to do a permanent setup for this later)

i had the following setup:

hiera-data:
```
---
one::head::ssh_pub_key: 'ssh pub key'
one::head::ssh_priv_key: 'ssh-dsa priv key'
one::oned::db: oneadmin
one::oned::db_user: oneadmin
one::oned::db_password: oneadmin
one::oned::db_host: localhost
one::oned::sunstone_listen_ip: '0.0.0.0'
one::oned::kvm_driver_emulator: '/srv/lib/something'
one::oned::kvm_driver_nic_attrs: '{blubber blah fasel}'
```

the fire up puppet several times with:
```puppet apply /etc/puppet/modules/one/spec/docker-int/one-head.pp```

which includes only this:
```
class { 'one':
  oned => true,
  node => false,
  sunstone => true,
}
```

and i only got the change on the first run and then there where no more changes in the runs afterwards

**Comment by jtriley** [comment]
Hmmm OK this might be something related to my environment then. I'll do some more testing on my side and update. Thanks!

**Comment by jtriley** [comment]
@rwaffen Turns out we had an old version of inifile (1.0.3) that seems to have been the culprit. After upgrading to latest 1.4.2 version this issue vanished. With that said, should we lock inifile >= 1.4.2?

**Pull request merged**
